// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Data.Migrations.DbContext
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505223414_AutoMigration_DemoUNLZ_20260505193403")]
    partial class AutoMigration_DemoUNLZ_20260505193403
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Data.Tables.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCompra");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Web.Data.Tables.CompraDetalle", b =>
                {
                    b.Property<int>("IdCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraDetalle"));

                    b.Property<int>("FechaTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImporteUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCompraDetalle");

                    b.ToTable("CompraDetalles");
                });

            modelBuilder.Entity("Web.Data.Tables.ConfiguracionEvento", b =>
                {
                    b.Property<int>("IdConfiguracionEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracionEvento"));

                    b.Property<int>("CantidadEntradas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaLimiteCompraEntradas")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracionEvento");

                    b.ToTable("ConfiguracionesEvento");
                });

            modelBuilder.Entity("Web.Data.Tables.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("int");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProvinciaIdProvincia")
                        .HasColumnType("int");

                    b.HasKey("IdEvento");

                    b.HasIndex("ProvinciaIdProvincia");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Web.Data.Tables.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Web.Data.Tables.TipoEvento", b =>
                {
                    b.Property<int>("IdTipoEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEvento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoEvento");

                    b.ToTable("TiposEvento");
                });

            modelBuilder.Entity("Web.Data.Tables.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Web.Data.Tables.Compra", b =>
                {
                    b.OwnsOne("Web.Data.Tables.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("CompraIdCompra")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FechaAlta")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaBaja")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FechaModificacion")
                                .HasColumnType("datetime2");

                            b1.Property<int>("IdUsuarioAlta")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioBaja")
                                .HasColumnType("int");

                            b1.Property<int?>("IdUsuarioModificacion")
                                .HasColumnType("int");

                            b1.HasKey("CompraIdCompra");

                            b1.ToTable("Compras");

                            b1.WithOwner()
                                .HasForeignKey("CompraIdCompra");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("Web.Data.Tables.Evento", b =>
                {
                    b.HasOne("Web.Data.Tables.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaIdProvincia");

                    b.Navigation("Provincia");
                });
#pragma warning restore 612, 618
        }
    }
}
